name: Build and Archive Artifact

on:
  push:
    branches:
    - main
  workflow_dispatch: # Manual trigger added here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Skeleton Artifact
      run: |
        mkdir -p artifact
        echo "Hello, World!" > artifact/hello.txt

    - name: Archive Artifact (Replace 'dist' with your build output directory)
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: artifact
