name: Download and Display Artifact

on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: "Owner/Repository name (e.g., 'my-org/my-repo')"
        required: true
      source_workflow_name:
        description: "Name of the workflow that created the artifact"
        required: false
      source_workflow_run_id:
        description: "Run ID of the workflow that created the artifact"
        required: false
      artifact_name:
        description: "Name of the artifact to download"
        required: true
env:
  REPO: ${{ github.event.inputs.source_repository }}
  WORKFLOW_NAME: ${{ github.event.inputs.source_workflow_name }}
jobs:
  download_and_display:
    runs-on: ubuntu-latest
    steps:
    - name: Grab Workflow ID
      id: get_workflow_id
      run: |
        WORKFLOW_ID=$(gh workflow list --repo "${{ env.REPO }}" --json id,name | jq -r '.[] | select(.name == "Build and Archive Artifact") | .id')
        echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_OUTPUT

    - name: Get Workflow Run ID
      id: get_workflow_run_id
      run: |
        WORKFLOW_RUN_ID=$(gh run list -w ${{ steps.get_workflow_id.outputs.workflow_id }} --repo ${{ env.REPO }} -L 1 --json databaseId | jq -r '.[] | .databaseId')
        echo "workflow_run_id=$WORKFLOW_RUN_ID" >> $GITHUB_OUTPUT

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        repository: ${{ github.event.inputs.source_repository }}
        run-id: ${{ steps.get_workflow_run_id.outputs.workflow_run_id }}

    - name: Display Artifact Contents
      run: ls -R .

    - name: Display specific file in artifact
      run: cat artifact/hello.txt
