name: Download and Display Artifact

on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: "Owner/Repository name (e.g., 'my-org/my-repo')"
        required: true
      source_workflow_name:
        description: "Name of the workflow that created the artifact"
        required: true
      source_workflow_run_id:
        description: "Run ID of the workflow that created the artifact"
        required: true
      artifact_name:
        description: "Name of the artifact to download"
        required: true

jobs:
  download_and_display:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        github-token: ${{ secrets.GH_PAT }} # Replace with your secret
        repository: ${{ github.event.inputs.source_repository }}
        run-id: ${{ github.event.inputs.source_workflow_run_id }}

    # - name: Display Artifact Contents
    #   run: ls -R ${{ github.event.inputs.artifact_name }}

    - name: Display specific file in artifact
      run: cat ${{ github.event.inputs.artifact_name }}/filename
