name: Download and Display Artifact

on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: "Owner/Repository name (e.g., 'my-org/my-repo')"
        required: true
      source_workflow_name:
        description: "Name of the workflow that created the artifact"
        required: false
      source_workflow_run_id:
        description: "Run ID of the workflow that created the artifact"
        required: false
      artifact_name:
        description: "Name of the artifact to download"
        required: true
env:
  REPO: ${{ github.event.inputs.source_repository }}
  WORKFLOW_NAME: ${{ github.event.inputs.source_workflow_name }}
jobs:
  download_and_display:
    runs-on: ubuntu-latest
    steps:

    - name: Grab Worklflow_id
      id: get_workflow_id
      run: |
        WORKFLOW_ID=$(gh workflow list --repo "$REPO" --json id,name | jq -r '.[] | select(.name == "'"$WORKFLOW_NAME"'") | .id')
        echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_OUTPUT


    - name: Get Workflow Run ID
      id: get_workflow_run_id
      run: |
        WORKFLOW_RUN_ID=$(gh run list -w 100153781 --repo jsandov/skeletonArtifactProducer -L 1 --json databaseId | jq '.[]| .databaseId')
        echo "The workflow id is: ${WORKFLOW_RUN_ID}"
        echo "WORKFLOW_RUN_ID=$WORKFLOW_RUN_ID" >> $GITHUB_OUTPUT

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        github-token: ${{ secrets.GH_PAT }} # Replace with your secret
        repository: ${{ github.event.inputs.source_repository }}
        run-id: ${{ steps.vars.get_workflow_run_id.outputs.WORKFLOW_RUN_ID }}

    - name: Display Artifact Contents
      run: ls -R .

    - name: Display specific file in artifact
      run: cat hello.txt


